AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  EmailGenerationLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: EmailGenerationLambda
      Runtime: java11
      Handler: com.murillo.alex.resignatorservice.Lambda.EmailGenerationLambda::handleRequest
      CodeUri: ResignatorService  # This points to the correct directory containing your Java code
      MemorySize: 512
      Timeout: 10
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /resignator
            Method: POST
            # CORS Configuration START
            Cors:
              AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
              AllowHeaders: "'content-type'"
              AllowOrigin: "'*'"
            # CORS Configuration END
